### PR TITLE
Refactor simple CTA block

### LINKED ISSUE #400: Home Page - CTA Bar - Vertical Alignment Issues
CTA Bar on the home page is not properly aligned vertically. 

Text Phone number and CTA button should all be center aligned horizontally with equal padding top and bottom.

Link: https://main--shredit--stericycle.aem.live/en-us 

image

### PR DESCRIPTION
**Pull request by kronnox**
Fix #400

Test URLs:
- Before: 
  - https://main--shredit--stericycle.aem.page/
  - https://main--shredit--stericycle.aem.page/en-us/service-locations/birmingham-usa
  - https://main--shredit--stericycle.aem.page/en-us/email/regularly-scheduled-paper-shredding-with-shred-it-protectplus
  - https://main--shredit--stericycle.aem.page/tools/sidekick/blocks/simple-cta
- After: 
  - https://issue-400--shredit--stericycle.aem.page/
  - https://issue-400--shredit--stericycle.aem.page/en-us/service-locations/birmingham-usa
  - https://issue-400--shredit--stericycle.aem.page/en-us/email/regularly-scheduled-paper-shredding-with-shred-it-protectplus
  - https://issue-400--shredit--stericycle.aem.page/tools/sidekick/blocks/simple-cta

### CODE REVIEW

**Review by MarquiseRosier — APPROVED** [review]

**Comment by colinvlasak** [comment]
@kronnox overall these look good! 

2 notes:


1. The CTA on the Need a One-tiem bulk clean out is too wide. Can we constrain it to be about 1/4 the width?

https://issue-400--shredit--stericycle.aem.page/en-us/email/regularly-scheduled-paper-shredding-with-shred-it-protectplus

image

2. I don't ever see us using this super slim with background layout on - https://issue-400--shredit--stericycle.aem.page/tools/sidekick/blocks/simple-cta

With the blue background it seems too compressed. Unless maybe it's grouped with another block that has same background?

Is there a use case you are aware of for this?
 
image

**Comment by colinvlasak** [comment]
@kronnox makes sense. Please sync the changes up to live once complete and I can review. 

Our IT department seems to block any of the https://issue-400--shredit--stericycle.aem.page type links after I have viewed them once.

**Comment by colinvlasak** [comment]
@kronnox once this is pushed live, can you ensure the refactored changes are applied to Sidekick Library as well?

https://main--shredit--stericycle.aem.page/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/simple-cta&index=0 and all the other variations under Simple CTA.

**Comment by MarquiseRosier** [comment]
@colinvlasak synced!

**Comment by colinvlasak** [comment]
@MarquiseRosier overall looks great. One small issue. On the mobile version the headings don't appear bold or as large. Can you confirm that the H heading style from desktop for each variation is being carried over to mobile? If so, can you confirm that the proper styles are being applied to H styles across mobile and desktop? e.g. if H3 is bold on desktop, it should be bold on mobile and tablet as well.


Examples
image
image


Mobile

image
image

**Pull request merged**
