### PR TITLE
Narrow icon changes

### LINKED ISSUE #466: Columns (narrow-icons) - Rendering Issues
The Columns (narrow-icons) block is not rendering properly on https://main--shredit--stericycle.aem.live/en-us/secure-shredding-services/one-off-shredding-service

1. The icons are much too small
2. They are not center aligned to the text
3. They are not evenly spaced

image

Should look like:

image

Mobile Rendering is Also off

image

Should be: 
image

### PR DESCRIPTION
**Pull request by jindaliiita**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #466 

Test URLs:
- Before: 
  - https://main--shredit--stericycle.aem.page/en-us/secure-shredding-services/one-off-shredding-service
- After: 
  - https://narrow-icon-change--shredit--stericycle.aem.page/en-us/secure-shredding-services/one-off-shredding-service

### CODE REVIEW

**Review by kronnox — CHANGES_REQUESTED** [review]
This needs a separate smaller icon size for tablet / mobile. Also you should probably use `var(--icon-size-xl)` instead of the hardcoded `4rem`. Otherwise LGTM

**Comment by jindaliiita** [comment]
> This needs a separate smaller icon size for tablet / mobile. Also you should probably use `var(--icon-size-xl)` instead of the hardcoded `4rem`. Otherwise LGTM

For small devices, they seem to be too small, which is why I maintained similar behavior for all screens.

**Comment by kronnox** [comment]
> For small devices, they seem to be too small, which is why I maintained similar behavior for all screens.

You are right. I adjusted my PR to match this behaviour.

The icon sizing for the column blocks seems to be very inconsistently done in general. Sometime it's set on the wrapper, sometimes on the image. This is bad. I think we wouldn't even need so many variants of the column block if we would just be using the `xl-icons` style on the blocks / sections instead. But I don't really want to touch this, since it feels like it could break a lot of stuff.

**Comment by bstopp** [comment]
@kronnox - is your review change required still valid? if not can you dismiss it?

**Pull request merged**
