### PR TITLE
2 footer

### LINKED ISSUE #2: Footer
image

image

### PR DESCRIPTION
**Pull request by allanhero**
Fix #2 

Test URLs:

- Before: https://main--shredit--aemsites.aem.page/en-us
- After: https://2-footer--shredit--aemsites.aem.page/en-us
- After: https://2-footer--stericycle-shared--aemsites.hlx.page/en-us

Comments:
To test the short version of the footer, I created a footer file called footer-short, which can be included as the official footer on the page for display. As for the CTA with the title Get Informed appears only in one of the variants, it should be added separately as a separate form.

Variants of the footer:
Variant 1 - [https://www.shredit.com/en-us](https://www.shredit.com/en-us)
Variant 2 - [https://www.shredit.com/en-us/marketing/shred-it-document-destruction](https://www.shredit.com/en-us/marketing/shred-it-document-destruction)

### CODE REVIEW

**Comment by dkuntze** [comment]
@allanhero can you fix the minor linting flags? Otherwise, it looks pretty good.

**Review by kronnox — CHANGES_REQUESTED** [review]
Overall looks quite good to me. Added a few comments

**Comment by allanhero** [comment]
> Overall looks quite good to me. Added a few comments

Thank you for your feedback. I have made the corrections. If you have any more recommendations, I would be happy to consider them.

**Review by kronnox — APPROVED** [review]

**Comment by seanathero** [comment]
@allanhero looks great. My only concern is around using pt and pc units which I'm seeing in some of the css. I realize you're matching current site, but I think my preference would be to use px instead. Thoughts @dkuntze @kronnox on this?

**Comment by dkuntze** [comment]
Px or rem would be the preference

**Comment by allanhero** [comment]
> Px or rem would be the preference

I'm working on this change!

**Comment by allanhero** [comment]
> Px or rem would be the preference

Issue fixed!

**Review by dkuntze — APPROVED** [review]

**Pull request merged**
