### PR TITLE
feat: Added support for including form block in a 2 column layout

### LINKED ISSUE #333: Industry Pages - 2 Column Layout W/ Form
Main content section should have form placeholder – this applies to all Who We Serve Pages
o	Example: https://main--shredit--stericycle.aem.live/en-us/who-we-serve/accountants 

image

### PR DESCRIPTION
**Pull request by ravise5**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #333 #329 

Test URLs:
- Before: 
  - https://main--shredit--stericycle.aem.page/en-us/secure-shredding-services/drafts/one-off-shredding-service
- After: 
  - https://form-col--shredit--stericycle.aem.page/en-us/secure-shredding-services/drafts/one-off-shredding-service

### CODE REVIEW

**Comment by colinvlasak** [comment]
@ravise5 solution seems to make sense but rendering is off

- The content (text and form should fit within the margins of the site. Currently it expands while past and doesn't align with the content. 
- The gray background should fill the entire space - there should be no white around it. 
- There is too much padding on the top and bottom of this section
- It should look exactly like: https://www.shredit.com/en-us/secure-shredding-services/one-off-shredding-service 

image

**Comment by ravise5** [comment]
@colinvlasak addressed these comments. Please review.

**Comment by ravise5** [comment]
@colinvlasak all issue addressed.

**Comment by colinvlasak** [comment]
@ravise5 Overall looks good. 2 notes below. 

The text is bleeding into the toggle on smaller screen sizes. Can you have it stack like it does on mobile once there isn't enough space to show the label and toggle on one line?

image

This may be more for @MarquiseRosier but the page is still missing the ecomm box and CTA below the form. Please see that it is added.

image

**Comment by ravise5** [comment]
@colinvlasak it does stack, let me tweak the media query width to do this earlier then
image

**Review by jalagari — APPROVED** [review]

**Pull request merged**
