### PR TITLE
Issue486: fix forms mobile layout

### LINKED ISSUE #486: Mobile - Inline Form Rendering Issues
There are a number of front end of form rendering issues on mobile

1. Toggle button appearing split on https://main--shredit--stericycle.aem.live/en-us/offer
image

2. Form Stretched past edges of margin. This happening across most pages.

Example: https://main--shredit--stericycle.aem.live/en-us/who-we-serve/insurance

image

3. Uneven vertical spacing between email opt-in button

Vertical pace between final for field, Request Type toggle, opt-in checkbox section, and get a quote button should be even. 

Example: https://main--shredit--stericycle.aem.live/en-us/secure-shredding-services/one-off-shredding-service

image

### PR DESCRIPTION
**Pull request by ravise5**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #486 

Test URLs:
- Before: 
  - https://main--shredit--stericycle.aem.page/en-us/offer
- After: 
  - https://issue486--shredit--stericycle.aem.page/en-us/offer

### CODE REVIEW

**Comment by MarquiseRosier** [comment]
Hey guys @ravise5 @jalagari this is almost perfect just the buttons are overlaying the text

Screenshot 2024-11-17 at 7 51 44 PM

**Review by MarquiseRosier — CHANGES_REQUESTED** [review]
This happens in mobile -> when screen size is <  400px

Screenshot 2024-11-17 at 7 51 44 PM

**Review by jalagari — APPROVED** [review]

**Review by MarquiseRosier — CHANGES_REQUESTED** [review]
Hey @ravise5 @jalagari sorry aha I noticed the following bug! image

**Comment by ravise5** [comment]
@MarquiseRosier This is now fixed. Can you check?

**Review by MarquiseRosier — DISMISSED** [review]
There's one last thing i'm sure will be an issue! the navy background needs to cover the entire section/width of the view!

Screenshot 2024-11-19 at 1 48 24 AM

**Review by jalagari — APPROVED** [review]

**Comment by ravise5** [comment]
@MarquiseRosier The width issue is now fixed

**Comment by ravise5** [comment]
https://issue486--shredit--stericycle.aem.live/en-us/marketing/bulk-paper-shredding

**Pull request merged**
