### PR TITLE
fix video aspect ratio

### LINKED ISSUE #531: Video Component - Stretching
The video component appears to be stretching depending on the component it is placed in. On the home page its sctretching vertically. It should be the standard height the video is in, maintaining the aspect ratio. I have seen other instances where the video is stretched super wide to fill the space. The video should maintain the default aspect ratio and not stretch. 

image

### PR DESCRIPTION
**Pull request by MarquiseRosier**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #531 

Test URLs:
- Before: 
  - https://main--shredit--stericycle.aem.page/en-us/professional-shredders-shred-it-and-skateboarding-legend-tony-hawk-team-up
- After: 
  - https://vid-aspect--shredit--stericycle.aem.page/en-us/professional-shredders-shred-it-and-skateboarding-legend-tony-hawk-team-up

### CODE REVIEW

**Comment by colinvlasak** [comment]
@MarquiseRosier will this fix the rendering across the site? I noticed on the home page it's still stretched out veritcally.

image

Additionally can you ensure the row of videos are boxed and adhere to the page margins?

image

**Comment by jindaliiita** [comment]
@MarquiseRosier Can you please check the LHS score ?

**Comment by bstopp** [comment]
@jindaliiita - I pushed a fix for LHS.

**Review by jindaliiita — APPROVED** [review]

**Comment by bstopp** [comment]
@MarquiseRosier - i made an update to use the Video block to render the video. This helps with the lazy loading, preventing TBT issues.

@colinvlasak  - home page stretch should be gone.

**Comment by colinvlasak** [comment]
@bstopp home rendering looks better on the demo link. The issue with the 3 videos stretching too wide is still happening though.

image

**Comment by bstopp** [comment]
@colinvlasak - Fixed.

**Comment by colinvlasak** [comment]
@bstopp still seeing the videos spanning full width on my end. Tried reloading, new browser, incognito, etc. 

image

**Comment by bstopp** [comment]
Yeah, it helps if i *push* the change up to GitHub. Try now? :)

**Comment by colinvlasak** [comment]
@bstopp there we go!

**Pull request merged**
