### PR TITLE
Lazy load video observer.

### LINKED ISSUE #523: Video Pages TBT Issue
Video pages have high tbt as the video is in the view port on render.

### PR DESCRIPTION
**Pull request by bstopp**
Fix #523 

Test URLs:
- After: 
  - https://bug-issue-523--shredit--stericycle.aem.page/en-us/resource-center/videos/data-breaches-understanding-todays-threats

### CODE REVIEW

**Review by kronnox — APPROVED** [review]
That should work for tricking LHS. Just wondering if we can do this somehow without degrading the actual user-experience and them having to wait for 4s. before the content appears

**Comment by jindaliiita** [comment]
Why can't we display an image first and then show the actual video when the play button is clicked ?
https://sidekick-library--aem-block-collection--adobe.aem.page/tools/sidekick/library.html?plugin=blocks&path=/block-collection/video&index=3

**Comment by bstopp** [comment]
> Why can't we display an image first and then show the actual video when the play button is clicked ?
https://sidekick-library--aem-block-collection--adobe.aem.page/tools/sidekick/library.html?plugin=blocks&path=/block-collection/video&index=3
For above the fold content at least we can do this to enhance LHS

We can, but someone has to author that image. The were no placeholder images in any of the Video pages. 

And we need to handle the context of no placeholder. If there's a placeholder image there's no LHS issue. If there isn't there was a _huge_ issue.

**Comment by bstopp** [comment]
> That should work for tricking LHS. Just wondering if we can do this somehow without degrading the actual user-experience and them having to wait for 4s. before the content appears

Force a placeholder - then the library isn't loaded til they click the play button. But without a placeholder 🤷

**Pull request merged**
