### PR TITLE
Fix wistia color

### LINKED ISSUE #334: Video Embed - Blue
•	Video embed should be blue on SID website (currently green on EDS). Green is for Stericycle embeds.

image

### PR DESCRIPTION
**Pull request by MarquiseRosier**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #334 

Test URLs:
- Before: 
  - https://main--shredit--stericycle.aem.page/en-us/who-we-serve/insurance
- After: 
  - https://fix-wistia-color--shredit--stericycle.aem.page/en-us/who-we-serve/insurance

### CODE REVIEW

**Comment by jindaliiita** [comment]
@MarquiseRosier You need to add one more variant of video block with different color as green color is also being used on other pages.

**Comment by MarquiseRosier** [comment]
> @MarquiseRosier You need to add one more variant of video block with different color as green color is also being used on other pages.



> @MarquiseRosier You need to add one more variant of video block with different color as green color is also being used on other pages.

I don't think this is necessary right now because there's more than one type of video; other than Wistia embeds.

**Comment by jindaliiita** [comment]
@MarquiseRosier This page contains a green-colored video: https://main--shredit--stericycle.aem.live/en-us/secure-shredding-services/myshredit.

Perhaps we can ask @colinvlasak for his thoughts, as ideally, the color scheme should be consistent across the website.

**Comment by colinvlasak** [comment]
@jindaliiita @MarquiseRosier all Wista embeds should be the blue colour for the Shred-it site. 

When we migrate Stericycle in the future the embeds on the Stericycle site will be the green colour.

**Review by jindaliiita — APPROVED** [review]

**Pull request merged**
